//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3_CookingRecipe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int IdComment { get; set; }
        public int IdUser { get; set; }
        public string Text { get; set; }
        public int IdRecipe { get; set; }
        public bool Status { get; set; }
    
        public virtual CookingRecipe CookingRecipe { get; set; }
        public virtual User User { get; set; }
    }
}
