//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3_CookingRecipe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseCookingJameEntities1 : DbContext
    {
        public DatabaseCookingJameEntities1()
            : base("name=DatabaseCookingJameEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievements { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CookingRecipe> CookingRecipes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Tip> Tips { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<DetailsEvent> DetailsEvents { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
    }
}
