//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3_CookingRecipe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tip
    {
        public int IdTip { get; set; }

        [Required(ErrorMessage = "Name tip is required!")]
        [RegularExpression(@"\S+.*", ErrorMessage = "Name tip must not contain a leading space!")]
        public string NameTip { get; set; }
        public string Img { get; set; }

        [Required(ErrorMessage = "Describe is required!")]
        [RegularExpression(@"\S+.*", ErrorMessage = "Describe must not contain a leading space!")]
        public string Describe { get; set; }
    }
}
